spring.datasource.url=jdbc:postgresql://dpg-d9ftms3eo5us738mh2n0-a.frankfurt-postgres.render.com/gamehub_1rzk
spring.datasource.username=gamehub_user
spring.datasource.password=gWuKvH7sjM6PqboKDeXSetJC9dd8IcoU

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect